blank_issues_enabled: false

contact_links:
  - name: Documentation
    url: https://jihoonme.github.io/swift-html/main/documentation/html/
    about: Read the HTML's documentation
  - name: Discord
    url: https://discord.com/users/649233319820787712
    about: discord chat
